### PR TITLE
more BBC Three related changes

### PR DESCRIPTION
**Pull request by BrianG61UK**
Move London Live to 173 when outside London

### CODE REVIEW

**Comment by BrianG61UK** [comment]
Closing this for now.

**Comment by BrianG61UK** [comment]
Okay. Opening again, seem to be okay.

**Comment by BrianG61UK** [comment]
Has this been rejected as unsuitable?
If so is it because it's such a mess with multiple commits?
Is it worth me closing this PR and doing it again with a better explanation of why I chose channel 173?

**Comment by AbuBaniaz** [comment]
As far as I can see, net result of your commit is to stop London live going to 117. There is nothing changed about BBC three.

Please explain more on forum.

 The multiple commits are not really an issue for me as I edit your commit titles and remove the extra commit titles when squashing.

**Comment by BrianG61UK** [comment]
The reason I did it as BBC Three related is just that it's because of BBC Three taking 117 that 117 is no longer any good for London Live.

Closing. Will discuss on forum.

**Comment by BrianG61UK** [comment]
CLOSED to be re-submitted later.

**Comment by BrianG61UK** [comment]
See:
https://www.world-of-satellite.com/showthread.php?65025

**Pull request closed without merging**
