### PR TITLE
Movistar+ multiple regions

### PR DESCRIPTION
**Pull request by miberian**
Changes to provider files to support region 0x82 and merge with 0x83. This produces official channel order. This is now achieved without code changes.

### CODE REVIEW

**Comment by Huevos** [comment]
Ok, but in one file, not two...

And you wanted 0x82 and 0x83 at the same time, right?

**Comment by miberian** [comment]
Yes both 0x82 and 0x83 are required to get the full channel list. I don’t believe this can be done in a single xml without code changes to dvbscanner.

**Comment by miberian** [comment]
And please note that since the new file depends on the existing/main one there is no  impact to usability. Users will still see a single provider in the UI.

Downside of this approach compared to code changes is that it takes twice the time for processing.

**Comment by Huevos** [comment]
Ok, let me look at it.

**Comment by Huevos** [comment]
<visibleserviceflag ignore="1"/>

Why do you remove this?

**Comment by miberian** [comment]
The main file now has to be configured for 0x82 to produce the correct channel list. Descriptor 0x82 does not have visible_service_flag so I removed the configuration from that file. It is still required for 0x83 so the configuration remains as the previous version in sat_192_movistar_plus_esp_0x83.xml.

**Comment by Huevos** [comment]
Please see latest commits (in particular):
https://github.com/oe-alliance/AutoBouquetsMaker/commit/cf08f3ff2b5e2a65a7c14ba1d8f132da3f07a283
https://github.com/oe-alliance/AutoBouquetsMaker/commit/5c0a58a3781926eac5a2eef348f09f6e51f4a466

But obviously make sure you test with all commits.

**Comment by miberian** [comment]
No longer required.

**Pull request closed without merging**
