### PR TITLE
BBC Scotland HD swap

### PR DESCRIPTION
**Pull request by BrianG61UK**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
@BrianG61UK 
What region are you using? I am getting channels 115/844 with Scottish East SD custom.

**Comment by BrianG61UK** [comment]
I'm using, IIRC, Thames Valley South.
Yes, it looks like I overlooked that while SD is now 115 or 187, HD is always 844.
Give me a few minutes, and I'll add the change,

**Comment by BrianG61UK** [comment]
@AbuBaniaz I think we could remove some of the conditionals too, but if it's okay with you, I suggest leaving them, at least for the time being.

**Comment by AbuBaniaz** [comment]
Better to leave them in IMO. Better not to swap than swap with an unintended one.

**Comment by BrianG61UK** [comment]
@AbuBaniaz I think we're ready to go then?

**Comment by AbuBaniaz** [comment]
> @AbuBaniaz Exactly. I think we're ready to go then?
Relax. We have things out of this hobby. I had to rename your pull request, squash the commits and then merge it.  I am not using Work PC for this kind of thing. If you had done it that way, I would have merged it on my phone.

You are doing some good work. Keep it up. Don't let our having to go to work and not merge the pull request frustrate you. You can use the file on your receiver until we merge it.

**Pull request merged**
