### PR TITLE
When "Add provider name to bouquets" is enabled the " - All channels" should be omitted

### PR DESCRIPTION
**Pull request by Azureit**
When "Add provider name to bouquets" is enabled the " - All channels" should be omitted, it make sense only when the bouquet is a subset of All channels.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Although it might makes sense for providers with no sections, it doesn't do so for the ones with sections or the FTA/HD bouquets

As it is now
all channels

With the changes
all channels azureit

If I hide the sections
all channels azureit 2

**Comment by AbuBaniaz** [comment]
As it stands, it does not look right for the providers with sections, FTA, etc. 

Are you able to tweak it?

**Comment by AbuBaniaz** [comment]
@noguxi @Azureit 
Your comment has disappeared. I don't have a problem with this change.  There is no adverse affect for me. Attached are pictures of a setup, still looks fine to me.



@Huevos @andyblac @skaman @peterfdej @ViX-Sicilian 
Any objections to merging this?

**Comment by Huevos** [comment]
I don't understand what the point of this commit is.

**Comment by Huevos** [comment]
And why are you doing weird things like this: `(provider_config.flags & 0xdf) == 1`?

Should be: `provider_config.isMakeNormalMain()`

**Comment by Huevos** [comment]
So in providersconfig create a new method. e.g. isMakeOnlyNormalMain.

**Comment by AbuBaniaz** [comment]
The "all channels" text is pointless for providers with no other sections/bouquets. We don't need an extra option to inhibit the text.

**Comment by Huevos** [comment]
> The "all channels" text is pointless for providers with no other sections/bouquets. We don't need an extra option to inhibit the text.

You obviously have no clue what I am about.

**Comment by AbuBaniaz** [comment]
> You obviously have no clue what I am about.

Let's agree to disagree about that. 
All the best to you and your family.

**Comment by AbuBaniaz** [comment]
@noguxi
If you want to resubmit it with the requested changes, please do so from your new account.

**Comment by Huevos** [comment]
This PR is not even against the current version of the repo.

**Pull request closed without merging**
