### PR TITLE
Add spanish translations

### PR DESCRIPTION
**Pull request by spaJR**
Add spanish translations

### CODE REVIEW

**Comment by spaJR** [comment]
msgid "Are you sure you want to remove all bouquets created by ABM?"
msgstr "Estás seguro que quieres borrar todos los favoritos creados por ABM?"

msgid "Really close without saving settings?"
msgstr "Estás seguro que quieres cerrar sin guardar cambios?"

msgid "ABM log file has been saved to the tmp directory"
msgstr "Archivo log guardado en carpeta tmp"

Wrong tense. Why do you think is wrong?

msgid "yes (only HD)"
msgstr "si (solo HD)"

typo for si? SOLVED

"This option has several choices "Yes", (create a bouquet with all the "
"channels in it), "Yes HD only", (will group all HD channels into this "
"bouquet), "Custom", (allows you to select your own bouquet), "No", (do "
"not use a main bouquet)"

msgstr "Esta opción tiene varias opciones \ "Si", (crear una lista de favoritos"
"con todos los canales dentro), "Si, solo HD", (agrupar todos los canales HD en"
"esta lista), "Personalizado", (te permite seleccionar tu propia lista), "No", (no "
"usar una lista principal)"

typo? 'selecionar to propia lista'. SOLVED

**Comment by AbuBaniaz** [comment]
I asked daughter my to check.
There are questions where you are being asked if you are sure, rather than just if you want to.

Please ignore tense comment. However, this line has no reference to ABM.
msgstr "Archivo log guardado en carpeta tmp"

**Comment by spaJR** [comment]
You're right with questions where ask if you are sure. 

Do I make a new pull request?

**Comment by AbuBaniaz** [comment]
> Do I make a new pull request?
No, the changes you made got included

**Comment by AbuBaniaz** [comment]
You can close the issue you raised when ready

**Pull request merged**
