### PR TITLE
add TV3 to 292

### PR DESCRIPTION
**Pull request by davesayers2014**
Possibly add +1 channels in the bouquets 

Channel id,s
2808: , # RTE One+1
1025:, # TV3+1

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
dsayers pull

What text editor do you use?

**Comment by davesayers2014** [comment]
I edited it via edit on github

image

image

image


Im not sure why it does this

**Comment by AbuBaniaz** [comment]
You should use tabs, not spaces. I have added the channels here

https://github.com/oe-alliance/AutoBouquetsMaker/commit/1df35ad6c3741d68d30ecfde4cd3b40cc8b02c56

https://github.com/oe-alliance/AutoBouquetsMaker/commit/911d5c790f0988c188b2746b46eecddccf8ef605

**Comment by davesayers2014** [comment]
Ok ill close this request thanks ill look at how im editing

**Pull request closed without merging**
