### PR TITLE
[Sky 28.2E] BBC Red button changes and HD swap

### PR DESCRIPTION
**Pull request by BrianG61UK**
Do you think the HD swap is worth while?
Leave it out if you think it's not.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Can we wait for the swaps until after the Wimbledon ones launch?

**Comment by BrianG61UK** [comment]
> Can we wait for the swaps until after the Wimbledon ones launch?

Okay.

Shall I leave it to you to change the red button section to start at 970?
I guess I should have done it them separately, really.

**Comment by BrianG61UK** [comment]
Oh, you did :)
Sorry. I should have looked first.

**Comment by AbuBaniaz** [comment]
https://rxtvinfo.com/2023/bbc-axes-extra-red-button-service/

**Comment by BrianG61UK** [comment]
See #https://github.com/oe-alliance/AutoBouquetsMaker/pull/275

**Pull request closed without merging**
